name = "gadgets-store-uganda"
compatibility_date = "2025-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "gadgets-db"
database_id = "51d959a6-6fde-47c7-8fe1-2d250bf9a04e"

[[r2_buckets]]
bucket_name = "gadgets-images"
binding = "BUCKET"